Try to find browser detection with tools/validate_components.js
Summary:
It's important for client-side rehydration to render exactly the same React
component structure as the server-side. This is normally not a problem, unless
the component's render() output depends on something browser-specific.

If they *don't* match, then React will throw away the entire DOM tree under the
component mount point, and make a new DOM tree. A particularly bad case is the
following:

    1. User lands on a video page, using a server-side rendered video player
    2. User clicks play, and full-screens the video
    3. React rehydrates client-side, yielding a different DOM tree than the
       server. This forces a full-re-render of the video player.
    4. The user is forced out of full screen (I saw this behaviour on my
       iPhone).

One particularly annoying cause of server/client differences is feature
detection used to render something different for desktop and mobile.

Unlike the `window.location` or `window.KA`, this is not information webapp can
provide to react-render-server, since it doesn't know this information from the
browser.

Test Plan:
I originally made this change in `webapp/node_modules/react-render-server`, so
this test plan works there.

Inside webapp, I ran:

    tools/runtests.py --max-size=large react_util/server_side_render_test.py

And saw this:

    AssertionError: ./javascript/dashboard-package/bibliotron-homepage-with-nav.jsx #0: OK
    ./javascript/tutorial-video-package/tutorial-video-page.jsx #0: ERROR Error: There was a mismatch between the server and client rendered HTML. Server-side rendered components must not do feature feature detection, because the features detected will be different on the client and server!

    Here's where the server and client may differ
    (server) tid="..."></iframe><div class="poster-frame" data-reactid=".
    (mobile) tid="..."></iframe></div><div class="clarifications-containe
        at /Users/jlfwong/khan/webapp/genfiles/node_modules/react-render-server/tools/validate_components.js:130:23
        at Array.forEach (native)
        at fixtureFile (/Users/jlfwong/khan/webapp/genfiles/node_modules/react-render-server/tools/validate_components.js:72:14)
        at /Users/jlfwong/khan/webapp/genfiles/node_modules/react-render-server/tools/validate_components.js:150:22
        at Array.forEach (native)
        at inputJson (/Users/jlfwong/khan/webapp/genfiles/node_modules/react-render-server/tools/validate_components.js:149:15)
        at Socket.<anonymous> (/Users/jlfwong/khan/webapp/genfiles/node_modules/react-render-server/tools/validate_components.js:164:23)
        at emitNone (events.js:72:20)
        at Socket.emit (events.js:166:7)
        at endReadableNT (_stream_readable.js:903:12)
    ./javascript/tutorial-article-package/tutorial-article-page.jsx #0: OK
    ./javascript/tutorial-exercise-package/tutorial-exercise-page.jsx #0: OK
    ./javascript/content-library-package/curation-page.jsx #0: OK
    ./javascript/content-library-package/curation-page.jsx #1: OK
    ./javascript/content-library-package/curation-page.jsx #2: OK
    ./javascript/content-library-package/curation-page.jsx #3: OK
    ./javascript/page-package/stateful-header.jsx #0: OK
    ./javascript/style-package/style-guide.jsx #0: OK
    ./javascript/about-package/alumni.jsx #0: OK

Reviewers: emily, csilvers, john

Reviewed By: csilvers, john

Subscribers: john

Differential Revision: https://phabricator.khanacademy.org/D25868