Compute props before render(), to better catch errors.
Now we no longer even try to render a component when we can't load
(require) the fixtures file for it.  This has two big advantages:

1) We only print 'skipping' once for fixture-file errors, rather than
   many times (when using the -n flag)
2) Fixture errors don't interfere with the rate at which we introduce
   new requests when using the new -d flag.

Auditors: jlfwong

Test Plan:
   % tools/benchmark_ka_component.js -n2 -r1 ../webapp/javascript/editor-package/search-result-preview-widget.jsx.fixture.js ../webapp/javascript/content-library-package/components/concept-thumbnail.jsx.fixture.js ../webapp/javascript/learn-storm-package/kickoff-pledge.jsx ../webapp/javascript/learn-storm-package/kickoff-pledge.jsx.fixture.js
   % Skipping ../webapp/javascript/editor-package/search-result-preview-widget.jsx.fixture.js: Error: Cannot find module 'underscore'
   % Skipping ../webapp/javascript/learn-storm-package/kickoff-pledge.jsx: cannot infer component from /home/csilvers/khan/webapp/javascript/learn-storm-package/kickoff-pledge.jsx
   javascript/learn-storm-package/kickoff-pledge.jsx: 1383 90ms
   javascript/content-library-package/components/concept-thumbnail.jsx: 1679 87ms
   javascript/learn-storm-package/kickoff-pledge.jsx: 1384 83ms
   javascript/content-library-package/components/concept-thumbnail.jsx: 1682 87ms

The skipping of search-result-preview-widget only happens once!